# The Docker image that will be used to build your app
image: node:lts

# Functions that should be executed before the build script is run
before_script:
  - npm ci

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
    - npm run export
    - ls -l out  # List contents of the 'out' directory for debugging
  artifacts:
    paths:
      - out

pages:
  stage: deploy
  script:
    - ls -l  # List contents before moving
    - cp -r out/* public/
    - ls -l public  # List contents of the 'public' directory for debugging
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
